name: Publish Test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build tools
        run: |
          python3 -m pip install --upgrade build twine
      - name: Build package
        run: |
          python3 -m build
      - name: Publish package to PyPI
        shell: bash
        env:
          PYPI_API_TOKEN: ${{ secrets.testpypi_api_token }}
        run: |
          twine upload -u "__token__" -p "$PYPI_API_TOKEN" -r testpypi dist/*
